### ISSUE TITLE
两个人一起出现在一个画面怎么写

### ISSUE THREAD

**Issue by xueqing0622** [smthemex/ComfyUI_StoryDiffusion#13] opened 2024-06-12 10:47 UTC
[Bob] [Alice] on the road, near the forest;
我这样写，提示
Error occurred when executing Storydiffusion_Text2Img:

exceptions must derive from BaseException

File "F:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1055, in text2image
for value in gen:
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 718, in process_generation
) = process_original_prompt(character_dict, prompts.copy(), id_length)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\gradio_utils.py", line 508, in process_original_prompt
raise f"{character_key} not have enough prompt description, need no less than {id_length}, but you give {len(index_list)}"

Close

**Comment by xueqing0622** [comment] 2024-06-12 10:56
我看官方文档有两个角色一起的画面
不知道这个插件里面如何实现
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/114840118/1620a57d-e9b4-4aec-bc67-2dcd21a046b5)

**Comment by xueqing0622** [comment] 2024-06-12 11:08
好像可以了，是我写的时候不小心。
但是好像txt2img必须是7句话，不然就会上面的错误。
而且不过两个角色在一起，好像会污染。角色统一性就不好了

**Comment by smthemex** [comment] 2024-06-12 11:39
是角色的数量要一致，也就是你2个角色，下面有个角色数量那里必须是2，然后场景的里面，必须出现这两个角色的名字一次

**Comment by xueqing0622** [comment] 2024-06-12 11:43
好像低于7句话也可以，我也不知道为什么

**Comment by smthemex** [comment] 2024-06-12 12:10
跟句子长度没什么关系，要角色数量对得上。双角色出现在一个画面等后面更新

**Comment by xueqing0622** [comment] 2024-06-12 12:16
谢谢解答 期待双角色在同一画面更新
![Uploading image.png…]()

**Comment by xueqing0622** [comment] 2024-06-12 12:22
这样也u错，是什么原因。
![image](https://github.com/smthemex/ComfyUI_StoryDiffusion/assets/114840118/1b9a41f8-295b-4bc9-a6e1-89841bb303c7)

!! Exception during processing!!! exceptions must derive from BaseException
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 1055, in text2image
    for value in gen:
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\Storydiffusion_node.py", line 718, in process_generation
    ) = process_original_prompt(character_dict, prompts.copy(), id_length)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_StoryDiffusion\utils\gradio_utils.py", line 508, in process_original_prompt
    raise f"{character_key} not have enough prompt description, need no less than {id_length}, but you give {len(index_list)}"
TypeError: exceptions must derive from BaseException

**Comment by smthemex** [comment] 2024-06-12 13:09
角色关键词是img，在角色栏要有这个photomaker才生效，我去主页备注一下

**Comment by xueqing0622** [comment] 2024-06-13 00:45
感谢，期待双角色一起出现画面

**Comment by piovis2023** [comment] 2024-07-02 07:44
Is there a fix for this problem yet? Thank you

**Comment by smthemex** [comment] 2024-07-02 08:17
If using dual characters, each character needs to appear at least twice in the scene prompt words to avoid errors. This is not a bug, I have tried to fix it, but it will bring unexpected errors.
使用双角色时,需要每个角色在场景提示词中,出现2次以上(不包含双人同框)

**Closed** 2024-09-10 08:56 UTC
